services:
  myportfolio.api:
    image: ${DOCKER_REGISTRY-}myportfolioapi
    container_name: portfolio.api
    build:
      context: .
      dockerfile: src/MyPortfolio.API/Dockerfile
    depends_on:
      - portfolio.db
      - portfolio-seq
      - portfolio-blob-storage
  
  portfolio.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: portfolio.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Root1234
      - MSSQL_PID=Developer
    ports:
      - "2026:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  portfolio-seq:
    image: datalust/seq:latest
    container_name: portfolio-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "5341:5341"
      - "8082:80"
    volumes:
      - seq-data:/data

  portfolio-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: portfolio.blob-storage
    ports:
      - "10000:10000"
    volumes:
      - blob-storage-data:/data
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"

volumes:
  mssql-data:
  seq-data:
  blob-storage-data:
